#!/usr/bin/env bash

NAME=$(basename "$0")

usage()
{
    cat <<- EOF
 USAGE: $NAME [OPTIONS]
 OPTIONS:
     --help                  Display this message
     --sxhkd                 Reload SXHKD
     --picom                 Reload Picom
     --polybar               Reload Polybar
 Without any options the help message will be prompted.
EOF
}

# chech if the process is present like this:
# $(echo $(/bin/ps -e | grep sxhkd) | awk '{print $4}') = 'sxhkd'

for arg in "$@"; do
    case $arg in
        --help)
            usage
            exit 0
            ;;
        --sxhkd)
            if [[ -x "$(command -v sxhkd)" ]]; then
                killall -q sxhkd
                while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
                sxhkd &
            fi
            ;;
        --picom)
            if [[ -x "$(command -v picom)" ]]; then
                killall -q picom
                while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
                picom --daemon --experimental-backends &
            fi
            ;;
        --polybar)
            if [[ -x "$(command -v polybar)" ]]; then
                killall -q polybar
                while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
                polybar -c $SCRIPTPATH/polybar.ini master &

                if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
                    polybar -c $SCRIPTPATH/polybar.ini slave &
                fi
            fi
            ;;
    esac
done

(( $# == 0 )) && "$0" --help

exit 0
