#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"




## UNLOAD BACKGROUND & THEME
############################

if [ -x "$(command -v feh)" ]; then
    feh --bg-scale $SCRIPTPATH/down.jpg
fi
echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe




## KILL SOME
############

killall -q picom
killall -q polybar
