#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"




## LAST RUNNING THEME
#####################

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down




## KEYLAYOUT
############

setxkbmap -layout it  # gb,it,us
xmodmap ~/.Xmodmap




## MONITORS, POLYBAR, WALLPAPER, PICOM
######################################

$SCRIPTPATH/leftwm-polybar $($SCRIPTPATH/leftwm-monitor)
$SCRIPTPATH/leftwm-wallpaper
$SCRIPTPATH/leftwm-picom

echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe




## CONNECTIONS
##############

[[ -x "$(command -v nm-applet)" ]] && nm-applet &
[[ -x "$(command -v blueman-applet)" ]] && blueman-applet &
