.
.TH bte "1" "June 2022" "bte" "User Commands"
.SH NAME
bte \- text editor
.SH SYNOPSIS
.B bte
.SH DESCRIPTION
A simple text editor written in posix shell.
.PP
.SH "Usage"
.
.nf

Arrow Keys : cursor movement
Pg Up      : move up a page
Pg Dwn     : move down a page

Backspace  : delete the character before the cursor
Delete     : delete the character under the cursor

Ctrl+u     : undo action
Ctrl+r     : redo action

Ctrl+o     : save file
Ctrl+x     : quit bte
